name             "skeleton"
maintainer       " / TYPO3 Association"
maintainer_email "@typo3.org"
license          "Apache 2.0"
description      "Installs/configures something"
version          "0.1.0"
recipe           "skeleton::default", "Installs/configures something"
